### ISSUE TITLE
error build: Missing required module 'CNIOAtomics'

### ISSUE THREAD

**Issue by bill20509** [portto/blocto-ios-sdk#34]
Env:
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
Xcode: Version 14.0.1 (14A400)
macOS Monterey: Version 12.6

Reproduce steps: 
git clone git@github.com:portto/blocto-ios-sdk.git
cd blocto-ios-sdk/Example
pod install:
Analyzing dependencies
Pre-downloading: `FCL-SDK` from `https://github.com/portto/fcl-swift.git`, commit `6f0a59dfa2bdaa23fdf69194ecd8c2ffe35cce7c`
Pre-downloading: `SolanaWeb3` from `https://github.com/portto/solana-web3.swift.git`, commit `420ddd0eb04a62071265bf530cb55cfc61cc82eb`
Pre-downloading: `web3.swift` from `https://github.com/portto/web3.swift.git`, commit `6a9d8d655fde7e8300d011e3781bb7176b34a9ed`
Downloading dependencies
Installing Alamofire (5.6.2)
Installing BigInt (5.2.0)
Installing BloctoSDK (0.3.9)
Installing CGRPCZlibp (1.8.2)
Installing CNIOAtomics (2.40.0)
Installing CNIOBoringSSL (2.19.0)
Installing CNIOBoringSSLShims (2.19.0)
Installing CNIODarwin (2.40.0)
Installing CNIOHTTPParser (2.40.0)
Installing CNIOLinux (2.40.0)
Installing CNIOWindows (2.40.0)
Installing Cadence (0.4.0)
Installing CryptoSwift (1.5.1)
Installing EthereumSignTypedDataUtil (0.1.2)
Installing FCL-SDK (0.1.0)
Installing FlowSDK (0.4.0)
Installing GenericJSON (2.0.1)
Installing Logging (1.4.0)
Installing Runtime (2.2.2)
Installing RxCocoa (6.5.0)
Installing RxRelay (6.5.0)
Installing RxSwift (6.5.0)
Installing SnapKit (5.6.0)
Installing SolanaWeb3 (0.0.4)
Installing SwiftNIO (2.40.0)
Installing SwiftNIOConcurrencyHelpers (2.40.0)
Installing SwiftNIOCore (2.40.0)
Installing SwiftNIOEmbedded (2.40.0)
Installing SwiftNIOExtras (1.11.0)
Installing SwiftNIOFoundationCompat (2.40.0)
Installing SwiftNIOHPACK (1.22.0)
Installing SwiftNIOHTTP1 (2.40.0)
Installing SwiftNIOHTTP2 (1.22.0)
Installing SwiftNIOPosix (2.40.0)
Installing SwiftNIOSSL (2.19.0)
Installing SwiftNIOTLS (2.40.0)
Installing SwiftNIOTransportServices (1.12.0)
Installing SwiftProtobuf (1.19.1)
Installing SwiftyJSON (5.0.1)
Installing TweetNacl (1.0.2)
Installing _NIODataStructures (2.40.0)
Installing gRPC-Swiftp (1.8.2)
Installing secp256k1.swift (0.1.4)
Installing secp256k1Swift (0.7.4)
Installing secp256k1Wrapper (0.0.5)
Installing web3.swift (0.9.3)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 46 total pods installed.

open BloctoSDK.xcodeproj
Click Run button

And I get these errors:
~/blocto-ios-sdk/Example/BloctoSDK/ABIFunctions.swift error build: Missing required module 'CNIOAtomics'
~/blocto-ios-sdk/Example/BloctoSDK/Models/ExplorerURLType.swift error build: Missing required module 'CNIOAtomics'

Anything I missed?

**Comment by andrew54068** [comment]
Try open project with BloctoSDK.xcworkspace which will be generated after `pod install`.


Also we use `Gemfile.lock` to lock version of cocoapods, so using
```
bundle install

bundle exec pod install
```
is more recommend if `Bundler` is installed.

I've tried to reproduce the issue above with Xcode 14.0 & Xcode 14.1 beta 2 but they all work as expected.
Feel free to tell us if it can't be solved.

**Comment by bill20509** [comment]
Thanks, It work!
